### ISSUE TITLE
no binding mode indicator showing

### ISSUE THREAD

**Issue by yrmsa** [adriankarlen/neobrutal-zebar#32]
I’ve noticed the bar currently doesn’t display an indicator showing which binding mode is active (pause and resize). there’s no visible way for users to see which one is currently active on the bar.

I’d be happy to work on a pull request for this feature if it aligns with the project goals.

**Comment by adriankarlen** [comment]
Hi! Sure I don't mind having that added, I'd say that it could be added next to the direction indicator.
