### ISSUE TITLE
Failed to fetch dynamic configuration

### ISSUE THREAD

**Issue by 0xJWLabs** [adriankarlen/neobrutal-zebar#9]
I got this error Failed to fetch dynamic configuration

This is on my global_styles

```css
@import "http://asset.localhost/C%3A%2FUsers%2F0xJWL%2F%2Fglzr%2Fzebar.styles%2Fglobal.css";
```

And on global.css
```css
@import "http://asset.localhost/C:/Users/0xJWL/.glzr/zebar/styles/themes/catppuccin.css";
@import "http://asset.localhost/C:/Users/0xJWL/.glzr/zebar/styles/config.css";
@import "http://asset.localhost/C:/Users/0xJWL/.glzr/zebar/styles/animations.css";
@import "http://asset.localhost/C:/Users/0xJWL/.glzr/zebar/styles/bar.css";
@import "http://asset.localhost/C:/Users/0xJWL/.glzr/zebar/styles/group-left.css";
@import "http://asset.localhost/C:/Users/0xJWL/.glzr/zebar/styles/group-center.css";
@import "http://asset.localhost/C:/Users/0xJWL/.glzr/zebar/styles/group-right.css";
```

**Comment by 0xJWLabs** [comment]
Now it does work, but it looks like this

![Errors](https://github.com/user-attachments/assets/da37370f-5105-45ba-aec8-2ff6e558c090)

**Comment by adriankarlen** [comment]
> ```css
> @import "http://asset.localhost/C%3A%2FUsers%2F0xJWL%2F%2Fglzr%2Fzebar.styles%2Fglobal.css";
> ```

On this import the encoding between `zebar` and `styles` is incorrect. It should be `zebar%2Fstyles`.

**Comment by 0xJWLabs** [comment]
Should I use your feat/adapt-v2 or wait until v2 is released?

**Comment by adriankarlen** [comment]
That one is very much not finished, so no I would not recommend using it yet.

**Comment by adriankarlen** [comment]
Closed as I've released V2 config now
